name: Waka Readme

on:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: zidansec/zidansec # optional, By default, it will automatically use the repository who's executing the workflow.
          
          
          
          
          
          - name: waka-readme-stats
  # You may pin to the exact commit or the version.
  # uses: miermontoto/waka-readme-stats@22fee3dcba60bc3f27b9ca3ddc7bbf3fd998ec68
  uses: miermontoto/waka-readme-stats@v5
  with:
    # GitHub access token with Repo scope
    GH_TOKEN: # default is ${{ github.token }}
    # Your Wakatime API Key
    WAKATIME_API_KEY: 
    # Show the list of OS Worked on In dev metrics
    SHOW_OS: # optional, default is True
    # Show the list of projects worked on in dev metrics
    SHOW_PROJECTS: # optional, default is True
    # Show the Editors used in dev metrics
    SHOW_EDITORS: # optional, default is True
    # Show the time zone in the dev metrics
    SHOW_TIMEZONE: # optional, default is True
    # Shows the number of commit graph in the dev metrics
    SHOW_COMMIT: # optional, default is True
    # Show the Coding language used in dev metrics
    SHOW_LANGUAGE: # optional, default is True
    # Show the Total Lines of code written Badge till date
    SHOW_LINES_OF_CODE: # optional, default is False
    # Show language or framework used across different repository
    SHOW_LANGUAGE_PER_REPO: # optional, default is True
    # 
    SHOW_LOC_CHART: # optional, default is True
    # show day of week you are most productive
    SHOW_DAYS_OF_WEEK: # optional, default is True
    # Shows the current profile views
    SHOW_PROFILE_VIEWS: # optional, default is True
    # Shows the short facts
    SHOW_SHORT_INFO: # optional, default is True
    # Show stats in your own language
    LOCALE: # optional, default is en
    # Git commit with your own name and email
    COMMIT_BY_ME: # optional, default is False
    # Repos you don't want to be counted
    IGNORED_REPOS: # optional, default is 
    # Git commit message
    COMMIT_MESSAGE: # optional, default is Updated with Dev Metrics
    # Show updated date
    SHOW_UPDATED_DATE: # optional, default is True
    # Show Total Time you have coded
    SHOW_TOTAL_CODE_TIME: # optional, default is True
